export const listTheme = [
  {
    name: 'cloud',
    image: '/assets/public/img/Theme-cloud.webp',
    selfBg: '#0078d4',
    selfText: '#ffffff',
    otherBg: '#f4f4f4',
    otherText: '#000000',
    header: '#5ccdff',
  },
  {
    name: 'family',
    image: '/assets/public/img/Theme-family.webp',
    selfBg: '#ca9157',
    selfText: '#ffffff',
    otherBg: '#f4f4f4',
    otherText: '#fffff',
    header: '#fc6c35',
  },
  {
    name: 'green',
    image: '/assets/public/img/Theme-green.webp',
    selfBg: '#4e8e81',
    selfText: '#ffffff',
    otherBg: '#0e1e03',
    otherText: '#ffffff',
    header: '#48cc5b',
  },
  {
    name: 'default',
    image: '#f8f8fa',
    selfBg: '#0d6efd',
    selfText: '#ffffff',
    otherBg: '#e8e8e8',
    otherText: '#00000',
    header: '#f4f4f4',
  },
];