import { IHero } from "./types/heroes";

export const test: IHero[] = [
  {
    id: 1,
    name: 'David',
    address: 'asdad',
    age: 21,
    gender: 'male',
    mail: 'asdas@gmail.com',
  },
  {
    id: 2,
    name: 'Ong Dev',
    address: 'asdadsad',
    age: 22,
    gender: 'female',
    mail: 'asdas@gmail.com',
  },
  {
    id: 3,
    name: 'Phan Dat',
    address: 'asdadsad',
    age: 23,
    gender: 'male',
    mail: 'asdas@gmail.com',
  },
  {
    id: 4,
    name: 'An',
    address: 'asdadsad',
    age: 24,
    gender: 'female',
    mail: 'asdas@gmail.com',
  },
  {
    id: 5,
    name: 'Hoa',
    address: 'asdadsad',
    age: 24,
    gender: 'female',
    mail: 'asdas@gmail.com',
  },
  {
    id: 6,
    name: 'Vi',
    address: 'asdadsad',
    age: 24,
    gender: 'male',
    mail: 'asdas@gmail.com',
  },
  {
    id: 7,
    name: 'Thai Anh',
    address: 'asdadsad',
    age: 24,
    gender: 'male',
    mail: 'asdas@gmail.com',
  },
  {
    id: 8,
    name: 'Tina',
    address: 'asdadsad',
    age: 24,
    gender: 'female',
    mail: 'asdas@gmail.com',
  },
  {
    id: 9,
    name: 'Tumer',
    address: 'asdadsad',
    age: 24,
    gender: 'female',
    mail: 'asdas@gmail.com',
  },
  {
    id: 10,
    name: 'Quoc Anh',
    address: 'asdadsad',
    age: 24,
    gender: 'male',
    mail: 'asdas@gmail.com',
  },
];